from shaders.PointFragmentShader import point_frag_shader
from shaders.WaterFragmentShader import water_frag_shader
from shaders.WaterVertexShader import water_vert_shader
from shaders.BedFragmentShader import bed_frag_shader
from shaders.BedVertexShader import bed_vert_shader